#!/bin/bash
# Comprehensive Security Scanning with Trivy
# Author: Jatin Songara
# Description: Automated vulnerability scanning for containers, filesystems, and IaC

set -euo pipefail

# Configuration
SEVERITY="${SEVERITY:-HIGH,CRITICAL}"
OUTPUT_FORMAT="${OUTPUT_FORMAT:-table}"
REPORT_DIR="./security-reports"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

check_trivy() {
    if ! command -v trivy &> /dev/null; then
        log_error "Trivy is not installed"
        log_info "Install with: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin"
        exit 1
    fi
    log_success "Trivy is installed: $(trivy --version | head -n1)"
}

create_report_dir() {
    mkdir -p "$REPORT_DIR"
    log_info "Reports will be saved to: $REPORT_DIR"
}

scan_filesystem() {
    log_info "Scanning filesystem for vulnerabilities..."
    
    trivy fs \
        --severity "$SEVERITY" \
        --format "$OUTPUT_FORMAT" \
        --output "$REPORT_DIR/filesystem-scan-${TIMESTAMP}.txt" \
        .
    
    # Generate JSON report
    trivy fs \
        --severity "$SEVERITY" \
        --format json \
        --output "$REPORT_DIR/filesystem-scan-${TIMESTAMP}.json" \
        .
    
    log_success "Filesystem scan completed"
}

scan_docker_image() {
    local image=$1
    log_info "Scanning Docker image: $image"
    
    trivy image \
        --severity "$SEVERITY" \
        --format "$OUTPUT_FORMAT" \
        --output "$REPORT_DIR/image-scan-${image//\//-}-${TIMESTAMP}.txt" \
        "$image"
    
    # Generate JSON report
    trivy image \
        --severity "$SEVERITY" \
        --format json \
        --output "$REPORT_DIR/image-scan-${image//\//-}-${TIMESTAMP}.json" \
        "$image"
    
    log_success "Image scan completed for: $image"
}

scan_iac() {
    log_info "Scanning Infrastructure as Code..."
    
    # Scan Terraform
    if [ -d "terraform" ] || [ -f "*.tf" ]; then
        trivy config \
            --severity "$SEVERITY" \
            --format "$OUTPUT_FORMAT" \
            --output "$REPORT_DIR/iac-terraform-${TIMESTAMP}.txt" \
            .
        
        log_success "Terraform scan completed"
    fi
    
    # Scan Kubernetes manifests
    if [ -d "kubernetes" ] || [ -f "*.yaml" ]; then
        trivy config \
            --severity "$SEVERITY" \
            --format "$OUTPUT_FORMAT" \
            --output "$REPORT_DIR/iac-kubernetes-${TIMESTAMP}.txt" \
            ./kubernetes
        
        log_success "Kubernetes manifest scan completed"
    fi
    
    # Scan Dockerfiles
    if [ -f "Dockerfile" ] || [ -d "docker" ]; then
        trivy config \
            --severity "$SEVERITY" \
            --format "$OUTPUT_FORMAT" \
            --output "$REPORT_DIR/iac-dockerfile-${TIMESTAMP}.txt" \
            .
        
        log_success "Dockerfile scan completed"
    fi
}

scan_git_repo() {
    log_info "Scanning Git repository for secrets..."
    
    trivy repo \
        --severity "$SEVERITY" \
        --format "$OUTPUT_FORMAT" \
        --output "$REPORT_DIR/repo-scan-${TIMESTAMP}.txt" \
        .
    
    log_success "Repository scan completed"
}

generate_summary() {
    log_info "Generating security summary..."
    
    cat > "$REPORT_DIR/summary-${TIMESTAMP}.md" <<EOF
# Security Scan Summary
**Date:** $(date)
**Severity Levels:** $SEVERITY

## Scans Performed
- Filesystem vulnerability scan
- Docker image scan
- Infrastructure as Code scan
- Git repository scan

## Reports Generated
$(ls -1 "$REPORT_DIR"/*-${TIMESTAMP}.* | sed 's/^/- /')

## Next Steps
1. Review all HIGH and CRITICAL vulnerabilities
2. Update dependencies and base images
3. Fix IaC misconfigurations
4. Rotate any exposed secrets
5. Re-run scans after fixes

---
*Generated by Jatin Songara's Security Scanning Pipeline*
EOF
    
    log_success "Summary generated: $REPORT_DIR/summary-${TIMESTAMP}.md"
}

# Main execution
main() {
    echo "╔════════════════════════════════════════════════════════╗"
    echo "║     Comprehensive Security Scanning with Trivy         ║"
    echo "║              Author: Jatin Songara                     ║"
    echo "╚════════════════════════════════════════════════════════╝"
    echo ""
    
    check_trivy
    create_report_dir
    
    # Run scans
    scan_filesystem
    scan_iac
    scan_git_repo
    
    # Scan Docker images if specified
    if [ -n "${DOCKER_IMAGES:-}" ]; then
        IFS=',' read -ra IMAGES <<< "$DOCKER_IMAGES"
        for image in "${IMAGES[@]}"; do
            scan_docker_image "$image"
        done
    fi
    
    generate_summary
    
    echo ""
    log_success "All security scans completed!"
    log_info "Review reports in: $REPORT_DIR"
}

# Run main function
main "$@"
